### ISSUE TITLE
可以把引入的 monolog 版本号往上升级一下么？

### ISSUE THREAD

**Issue by willove** [fucongcong/co-framework#22]
用composer 加入 overtrue的 weixin SDK 最新版本时候报错了

`Can only install one of: monolog/monolog[1.23.0, 1.17.2]`

group-co用的` "monolog/monolog":"~1.17.1",`

而overtrue 用的` "monolog/monolog": "^1.22",`

这个就尴尬了。。

**Comment by fucongcong** [comment]
请更新composer update，master已经向上支持了
