### ISSUE TITLE
在swoole 2.0 以上  Group\Coroutine\task 是不是显得多余

### ISSUE THREAD

**Issue by xcwen** [fucongcong/co-framework#5]
namespace Group\Coroutine;  use Group\Handlers\ExceptionsHandler;  class Task {

**Comment by fucongcong** [comment]
1.如果用swoole 2.0的话，就不需要使用yield触发协程了，api内部调用自动会触发协程。此框架不适用swoole2.0以上版本。
2.1.9.*版本是相对稳定版本，2.0.*是腾讯团队在维护，如果选择看你自己取舍。
3.兼容性来说，1.9.*版本会更好。
4.你可以找找基本2.0以上版本开发的异步框架

**Comment by xcwen** [comment]
谢谢:>
